# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88bf1f829afb222070747255d1adfb71364df012b2e6c9fd0a38e23dc46d1c37705d4fed5b3767f84277c3ccaac9447d8f17873970f7e74c87ea4830b5c12548

test:
  secret_key_base: e6ecfb046257f769340d601230dba974888ce38ee6df6d27bb85877915af04b97100f524c3555b9ead561d56af8d7e2660137266043ec8bc8924320fb309b7ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
